[
    {
        "content": "<p>At a glance I don't see anything of note in the logs beside the exit code:</p>\n<p><a href=\"https://github.com/leanprover-community/mathlib4_docs/actions/runs/6959863254/job/18938068802#step:9\">https://github.com/leanprover-community/mathlib4_docs/actions/runs/6959863254/job/18938068802#step:9</a></p>",
        "id": 403681669,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1700696785
    },
    {
        "content": "<p>As a result, the docs are currently 3 days out of date</p>",
        "id": 403681793,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1700696878
    },
    {
        "content": "<p>I made a pr that should probably fix this yesterday <a href=\"https://github.com/leanprover-community/mathlib4/pull/8553\">#8553</a></p>",
        "id": 403682641,
        "sender_full_name": "Alex J. Best",
        "timestamp": 1700697598
    },
    {
        "content": "<p>Cc <span class=\"user-mention silent\" data-user-id=\"110524\">Scott Morrison</span></p>",
        "id": 403682749,
        "sender_full_name": "Alex J. Best",
        "timestamp": 1700697634
    }
]