[
    {
        "content": "<p>I have this code</p>\n<div class=\"codehilite\" data-code-language=\"import\"><pre><span></span><code>#check sub_self\n\nexample (x : ℤ) : x * 0 = 0 :=\ncalc\n  x * 0 = x * (1 - 1)   : by rw sub_self\n  ...   = x * 1 - x * 1 : mul_sub x 1 1\n  ...   = 0             : sub_self (x * 1)\n</code></pre></div>\n<p>I run <code>lean filename.lean</code></p>\n<p>And get</p>\n<p><code>sub_self : ∀ (a : ?M_1), a - a = 0</code></p>\n<p>I can't tell if this is telling my attempted proof has failed. Normally I get <code>error</code> or similar if my proof is incorrect. Is this merely an informative message?</p>",
        "id": 262216954,
        "sender_full_name": "Dan Piponi",
        "timestamp": 1637461221
    },
    {
        "content": "<p>If you run lean interactively (in VScode say) then that message should come with a line number, telling you that it is the output from the check line above the proof, which isn't relevant for the proof at all (except to help you write it !). So probably yes your proof is fine if lean isn't complaining. If you ever want to double check that lean didn't die you can give a name to your lemma (not an example) and then you can <code>#check my_lemma</code> to be sure</p>",
        "id": 262217387,
        "sender_full_name": "Alex J. Best",
        "timestamp": 1637462040
    },
    {
        "content": "<p>Ah! It's the check line! As I just copied and pasted the first part from an exercise I didn't take any notice of that line. Thanks.</p>",
        "id": 262218423,
        "sender_full_name": "Dan Piponi",
        "timestamp": 1637463921
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"459093\">Dan Piponi</span> has marked this topic as resolved.</p>",
        "id": 262218425,
        "sender_full_name": "Notification Bot",
        "timestamp": 1637463930
    }
]